(part "901-10040-1"
    (packageRef "901100401")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Amphenol")
    (property "Manufacturer_Part_Number" "901-10040-1")
    (property "Mouser_Part_Number" "523-901-10040-1")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=523-901-10040-1")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "RF Connector, SMA Straight PCB Jack, 50 Ohm")
    (property "Datasheet_Link" "")
    (property "symbolName1" "901-10040-1")
)
