(part "SX1262IMLTRT"
    (packageRef "QFN50P400X400X100-25N-D")
    (interface
        (port "1" (symbPinId 1) (portName "VDD_IN") (portType INPUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType GROUND))
        (port "3" (symbPinId 3) (portName "XTA") (portType INPUT))
        (port "4" (symbPinId 4) (portName "XTB") (portType INPUT))
        (port "5" (symbPinId 5) (portName "GND_2") (portType GROUND))
        (port "6" (symbPinId 6) (portName "DIO3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VREG") (portType OUTPUT))
        (port "8" (symbPinId 8) (portName "GND_3") (portType GROUND))
        (port "9" (symbPinId 9) (portName "DCC_SW") (portType OUTPUT))
        (port "10" (symbPinId 10) (portName "VBAT") (portType INPUT))
        (port "11" (symbPinId 11) (portName "VBAT_IO") (portType INPUT))
        (port "12" (symbPinId 12) (portName "DIO2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "DIO1") (portType INOUT))
        (port "14" (symbPinId 14) (portName "BUSY") (portType INOUT))
        (port "15" (symbPinId 15) (portName "NRESET") (portType INOUT))
        (port "16" (symbPinId 16) (portName "MISO") (portType OUTPUT))
        (port "17" (symbPinId 17) (portName "MOSI") (portType INPUT))
        (port "18" (symbPinId 18) (portName "SCK") (portType INPUT))
        (port "19" (symbPinId 19) (portName "NSS") (portType INPUT))
        (port "20" (symbPinId 20) (portName "GND_4") (portType GROUND))
        (port "21" (symbPinId 21) (portName "RFI_P") (portType INPUT))
        (port "22" (symbPinId 22) (portName "RFI_N") (portType INPUT))
        (port "23" (symbPinId 23) (portName "RFO") (portType OUTPUT))
        (port "24" (symbPinId 24) (portName "VR_PA") (portType INOUT))
        (port "25" (symbPinId 25) (portName "GND_5") (portType GROUND))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "SEMTECH")
    (property "Manufacturer_Part_Number" "SX1262IMLTRT")
    (property "Mouser_Part_Number" "947-SX1262IMLTRT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Semtech/SX1262IMLTRT?qs=XFmntM7Yc9eYt6yxTPughQ%3D%3D")
    (property "Arrow_Part_Number" "SX1262IMLTRT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/sx1262imltrt/semtech.html?utm_currency=USD&region=nac")
    (property "Description" "RF Transceiver LoRa, sub-GHz RF Transceiver 22dBm PA")
    (property "Datasheet_Link" "http://www.mouser.com/datasheet/2/761/DS_SX1261-2_V1.1-1307803.pdf")
    (property "symbolName1" "SX1262IMLTRT")
)
