M48
; DRILL file KiCad 10.0.5 date 2026-07-29T09:26:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-29T09:26:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X99.351Y-87.92
X105.131Y-87.92
T2
X91.651Y-81.0
X91.651Y-84.0
M30
