(part "TLV75533PDRVR"
    (packageRef "SON65P200X200X80-7N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EPAD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TLV75533PDRVR")
    (property "Mouser_Part_Number" "595-TLV75533PDRVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TLV75533PDRVR?qs=lc2O%252BfHJPVbmKlktYGVy6A%3D%3D")
    (property "Arrow_Part_Number" "TLV75533PDRVR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tlv75533pdrvr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "500-mA low-IQ small-size low-dropout (LDO) regulator")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tlv755p")
    (property "symbolName1" "TLV75533PDRVR")
)
