(part "BGS12WN6E6327XTSA1"
    (packageRef "BGS12WN6E6327XTSA1")
    (interface
        (port "1" (symbPinId 1) (portName "RF2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "RFIN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CTRL") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "BGS12WN6E6327XTSA1")
    (property "Mouser_Part_Number" "726-BGS12WN6E6327XTS")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/BGS12WN6E6327XTSA1?qs=unwgFEO1A6uim3e4emYLzg%3D%3D")
    (property "Arrow_Part_Number" "BGS12WN6E6327XTSA1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bgs12wn6e6327xtsa1/infineon-technologies-ag.html?utm_currency=USD&region=nac")
    (property "Description" "IC RF SWITCH SPDT 9GHZ TSNP6-10")
    (property "Datasheet_Link" "https://www.infineon.com/dgdl/Infineon-BGS12WN6-DataSheet-v01_00-EN.pdf?fileId=5546d4626b2d8e69016b89d2b3334727")
    (property "symbolName1" "BGS12WN6E6327XTSA1")
)
